# Generated by Django 3.2.11 on 2022-01-23 19:02

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(max_length=5, validators=[account.models.valid_zipcode]),
        ),
    ]
