# Generated by Django 3.2.11 on 2022-01-23 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('categories', models.ManyToManyField(to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.subcategory')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='idx_slug_category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('slug',), name='uq_slug_category'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['slug'], name='idx_slug_subcategory'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('slug',), name='uq_slug_subcategory'),
        ),
        migrations.AddIndex(
            model_name='style',
            index=models.Index(fields=['slug'], name='idx_slug_style'),
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(fields=('slug',), name='uq_slug_style'),
        ),
    ]
