# Generated by Django 3.2.11 on 2022-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220124_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
