#!/bin/bash

NAME="cms"
DIR=/home/ubuntu/django/cms
USER=ubuntu
GROUP=ubuntu
WORKERS=2
SOCKFILE=unix:/home/ubuntu/django/gunicorn.sock
DJANGO_SETTINGS_MODULE=cms.settings
DJANGO_WSGI_MODULE=cms.wsgi
LOG_LEVEL=debug
cd $DIR
source /home/ubuntu/django/django/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE

exec /home/ubuntu/django/django/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $WORKERS \
--user=$USER \
--group=$GROUP \
--bind=$SOCKFILE \
--log-level=$LOG_LEVEL \
--log-file=-
