# Generated by Django 3.2.11 on 2022-02-05 20:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField(default=datetime.date.today)),
                ('order_id', models.UUIDField(editable=False)),
                ('delivery_date', models.DateField(null=True)),
                ('order_completed', models.BooleanField(default=False)),
                ('tax', models.FloatField()),
                ('total_price', models.FloatField()),
                ('order_cancelled', models.BooleanField(default=False)),
                ('items', models.JSONField()),
                ('payment_intent', models.CharField(max_length=50, null=True)),
                ('payment_intent_client_secret', models.CharField(max_length=80, null=True)),
                ('payment_succeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='deliveryoption',
            index=models.Index(fields=['slug'], name='idx_slug_delivery_option'),
        ),
    ]
